name: Deploy Sqitch to AWS RDS (Dev)

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  deploy-dev:
    runs-on: windows-latest
    name: Deploy to Dev Environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install PostgreSQL client
      - name: Install PostgreSQL
        run: |
          choco install postgresql --version=17.5 -y
          echo "C:\Program Files\PostgreSQL\17\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Step 3: Install Strawberry Perl (needed for Sqitch on Windows)
      - name: Install Strawberry Perl
        run: choco install strawberryperl -y

      # Step 4: Install Sqitch
      - name: Install Sqitch
        run: |
          cpan App::Sqitch
          sqitch --version

      # Step 5: Set environment variables
      - name: Set environment
        run: |
          echo "PGUSER=${{ secrets.PGUSER }}" >> $env:GITHUB_ENV
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> $env:GITHUB_ENV
          echo "PGHOST=${{ secrets.PGHOST }}" >> $env:GITHUB_ENV
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> $env:GITHUB_ENV
          echo "PGPORT=${{ secrets.PGPORT }}" >> $env:GITHUB_ENV

      # Step 6: Deploy using Sqitch
      - name: Deploy with Sqitch
        run: |
          set "PGPASSWORD=${{ secrets.PGPASSWORD }}"
          sqitch deploy db:pg://$env:PGUSER@$env:PGHOST:$env:PGPORT/$env:PGDATABASE
